server:
  port: 8088
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/rentalproperty
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create


sql:
    init:
      data-locations:
        classpath: src/main/resources/db/data.sql
      schema-locations:
        classpath: src/main/resources/db/schema.sql