spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:rentalproperty}?allowMultiQueries=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changes/changelog-master.xml

logging:
  level:
    root: INFO
    com.example.rental_property: DEBUG
  file:
    name: rental_property.log

server:
  port: 8080
