spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/rentalproperty
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  logging:
    level:
     root: root

#  sql:
#    init:
#      data-locations:
#        classpath: db/data.sql
##      schema-locations:
##        classpath: db/schema.sql