spring:
  main:
    banner-mode: off

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db\changelog\changes\changelog-master.xml

