spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/rentalproperty
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none


  sql:
    init:
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql
      mode: always
